# Generated by Django 3.1 on 2023-05-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_auto_20230521_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='نام محصل اسلگ')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='توضیحات محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('images', models.ImageField(upload_to='photo/products', verbose_name='عکس محصول')),
                ('stock', models.IntegerField(verbose_name='تعداد موجود')),
                ('is_available', models.BooleanField(default=True, verbose_name='آیا موجود است')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('modifired_date', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول گذاری',
                'verbose_name_plural': 'محصول گذاری',
            },
        ),
    ]
