# Generated by Django 3.1 on 2023-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_old',
            field=models.IntegerField(null=True, verbose_name='قیمت قدیمی'),
        ),
    ]
