# Generated by Django 3.1 on 2023-05-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.IntegerField(max_length=11, null=True, unique=True),
        ),
    ]
