# Generated by Django 3.1 on 2023-05-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230520_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'پنل کاربری مدریت', 'verbose_name_plural': 'پنل کاربری مدیریت'},
        ),
        migrations.AlterField(
            model_name='accounts',
            name='date_join',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت '),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام کاربری'),
        ),
    ]
