# Generated by Django 3.1 on 2023-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته بندی ')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='مسیر حرکت ')),
                ('description', models.TextField(max_length=255, unique=True, verbose_name='توضیحات ')),
                ('cat_image', models.ImageField(unique=True, upload_to='photo/categories', verbose_name='عکس دسته بندی ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
    ]
