# Generated by Django 3.1 on 2023-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20230521_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='تقسیم بندی کردن  نام دسته بندی'),
        ),
    ]
